### ISSUE TITLE
Unable to submit code to GitHub

### ISSUE THREAD

**Issue by todoubled711** [discapp/discapp#12]
Chris,

I tried to submit the HTML last night. When I got to the last step to push changes it said I didn't have permissions. Would you be able to grant me permissions?

![image 1](https://user-images.githubusercontent.com/29343915/27253643-6b56ccda-5346-11e7-8562-8b372268b70c.png)

Thanks,
Todd

**Comment by cruoti** [comment]
@todoubled711 

You should have an outstanding invite to be a collaborator to the repo already.  Search your email that is linked to the GitHub account.  I couldn't see how to resend the invite.  So if you can't find it, I'll get rid of the invite and then remake it and hopefully it would email you again.

This might be the link to get to it, but I'm not sure. 
https://github.com/discapp/discapp/invitations

**Comment by cruoti** [comment]
@todoubled711 

Also, in general, the best practice is to create a new branch for your work, push it, and then submit a pull request on GitHub to merge it.  It's a few extra steps but it keeps track of everything a lot nicer.  Another big benefit is that everyone can review it before it gets merged in.  I wouldn't worry about it too much for this merge because you already have it set up, but in the future.

Refer to #11 for an example of a pull request.

**Comment by mrossi113** [comment]
@todoubled711 @cruoti I would create new branch for this `git checkout -b <branch name>`. The reason being is depending on what @todoubled711 has pull down for develop it could override code already in develop.  

@todoubled711 when you create a new branch to keep it updated with the develop branch. First have develop branch checkout than `git pull` this will pull anything that is new from the develop branch. Than checkout your branch `git checkout <branch name>` once in your branch you can merge the develop branch with your branch by `git merge develop` once your on your branch. 

Below are screenshot from another repo I have which use `git pull upstream develop` instead of `origin`: 
![screen shot 2017-06-17 at 12 17 51 pm](https://user-images.githubusercontent.com/19477691/27254502-9f82c598-5357-11e7-8084-0f7457d74434.jpg)
![screen shot 2017-06-17 at 12 18 10 pm](https://user-images.githubusercontent.com/19477691/27254506-a6efb908-5357-11e7-858e-f1dc8789d986.jpg)

@todoubled711 I'm not sure how much experience you have with Git. If you already now this completely ignore this.

**Comment by todoubled711** [comment]
Melissa and Chris,

Thanks for the help. I apologize I am not familiar with Git. Good and bad news I was able to submit the code but it was before seeing Melissa message. I am not sure what happened to the invite it was never to my email though, but the link Chris provided worked for me.

Thanks,
Todd

**Comment by mrossi113** [comment]
@todoubled711 

Chris don't worry about it and everything looks fine from your push to develop. If you any questions about Git let me now. It took some time for me to get handle on how Git works as well. Plus I had some great co-worker who would step me through some Git workflows that I've encounter over time.
